server:
  port: 8081

spring:
  application:
    name: mysecurity
#  security:
#    user:
#      name: user
#      password: 12345678
#      roles: USER, ADMIN
  datasource:
    driver-class-name: org.h2.Driver
    password: ""
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=true;DB_CLOSE_DELAY=-1
    username: sa
    initialization-mode: embedded
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  ldap:
    base: dc=imooc,dc=com
    embedded:
      base-dn: dc=imooc, dc=com
      ldif: classpath:test-ldap-server.ldif
      port: 8389
    urls: ldap://localhose:8389/

  messages:
    basename: messages
    encoding: UTF-8
